### ISSUE TITLE
Provide optional support for VSCode Dev Containers

### ISSUE THREAD

**Issue by tnmygrwl** [UMassCDS/PythonProjectTemplate#6]
As a developer
- I want to be able to use Linux-only packages on my local setup and not have to worry about equivalents for OSX and deal with the downstream issues.
- I want to develop inside Docker containers seamlessly as I would locally using the rich feature set of my IDE (VSCode).
So for that reason, I'd like support for doing development inside a Docker container using [VSCode's dev containers](https://code.visualstudio.com/docs/devcontainers/containers)

### Timebox [optional]
N/A

### Definition of Done 
- [ ] Add a `.devcontainer/devcontainer.json` or a `.devcontainer.json` to the root of the project
- [ ] Add a minimal sample config and link to Microsoft's documentation.
- [ ] Update documentation as needed (e.g. installing the dev containers extension on VS Code, outline of use cases/benefits of dev containers)

### Subtasks
N/A
